#pragma once
#include <stdint.h>
#include "gbsynth.h"

// Gen 1 cries (cries.h, generated by tools/gen_cries.py) played on GbSynth.
//
// No Arduino dependency, like gbsynth: the firmware pumps it into I2S, the
// emulator and the tests pump it into a buffer. Same code, same sound.
//
//   CryPlayer c;
//   if (c.begin(dex)) { uint32_t ms; while ((ms = c.step(syn))) render(ms); }
//
// step() starts whichever notes are due on the synth and returns how many ms
// the caller should render before calling again, 0 when the cry is over.

// True if this dex number has a cry (Kanto and Johto, 1-251; later generations
// are sampled audio on hardware and cannot be expressed as notes).
bool cryHas(int16_t dex);

class CryPlayer {
 public:
  bool begin(int16_t dex);
  uint32_t step(GbSynth &syn);
  bool done() const { return !active; }
  // Total length of the cry in ms, for tests and for UI that wants to wait it out.
  static uint32_t lengthMs(int16_t dex);

 private:
  const void *seq[3] = {0, 0, 0};   // CryNote arrays: pulse, pulse, noise
  uint8_t n[3] = {0, 0, 0};
  uint8_t idx[3] = {0, 0, 0};
  uint32_t at[3] = {0, 0, 0};       // ms at which each channel's next note starts
  uint32_t clock = 0;
  int16_t pitch = 0;
  uint16_t tempo = 256;
  const struct CryBase *base = nullptr;
  bool active = false;
};
