#!/usr/bin/env python3
"""Builds logo.h: the "TamaPoké" wordmark for the ABOUT page, from a TTF.

The firmware font is a 5x7 bitmap with no accents, so the title is rendered
once here and stored as a 2-bit index image: 0 clear, 1 yellow fill, 2 blue
outline, 3 navy drop shadow. Four pixels per byte, row-major, LSB first.

The Pokemon logo lettering is Nintendo/TPC artwork with no official font, so
pass a lookalike (a fan font such as "Pokemon Solid") that you have the right
to use. The font is NOT shipped; only the generated bitmap is.

    python3 tools/gen_logo.py --font /path/to/PokemonSolid.ttf
    python3 tools/gen_logo.py --font F.ttf --preview logo.png
"""
import argparse, os
from PIL import Image, ImageDraw, ImageFont, ImageFilter

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEXT = "TamaPoké"
W_MAX = 300          # fits the round panel at its centre line
OUTLINE, SHADOW = 4, 4


def render(font_path):
    size = 120
    while True:
        f = ImageFont.truetype(font_path, size)
        l, t, r, b = f.getbbox(TEXT)
        if r - l + 2 * OUTLINE + SHADOW <= W_MAX or size < 12:
            break
        size -= 2
    w, h = r - l + 2 * OUTLINE + SHADOW, b - t + 2 * OUTLINE + SHADOW
    mask = Image.new("L", (w, h), 0)
    ImageDraw.Draw(mask).text((OUTLINE - l, OUTLINE - t), TEXT, 255, font=f)
    fill = mask.point(lambda v: 255 if v > 127 else 0)
    k = 2 * OUTLINE + 1
    outline = fill.filter(ImageFilter.MaxFilter(k))
    shadow = Image.new("L", (w, h), 0)
    shadow.paste(outline, (SHADOW, SHADOW))
    img = Image.new("P", (w, h), 0)
    px = img.load()
    for y in range(h):
        for x in range(w):
            if fill.getpixel((x, y)): px[x, y] = 1
            elif outline.getpixel((x, y)): px[x, y] = 2
            elif shadow.getpixel((x, y)): px[x, y] = 3
    return img


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--font", required=True)
    ap.add_argument("--preview")
    a = ap.parse_args()
    img = render(a.font)
    w, h = img.size
    px = img.load()
    data = bytearray((w * h + 3) // 4)
    for i in range(w * h):
        data[i // 4] |= px[i % w, i // w] << (2 * (i % 4))
    if a.preview:
        pal = [(0, 0, 0), (0xFF, 0xCB, 0x05), (0x3B, 0x4C, 0xCA), (0x10, 0x15, 0x45)]
        rgb = Image.new("RGB", (w, h), (0xF7, 0xEE, 0xE6))
        for y in range(h):
            for x in range(w):
                if px[x, y]: rgb.putpixel((x, y), pal[px[x, y]])
        rgb.save(a.preview)
    lines = [", ".join("0x%02X" % b for b in data[i:i + 16]) for i in range(0, len(data), 16)]
    with open(os.path.join(ROOT, "logo.h"), "w") as f:
        f.write("// Generated by tools/gen_logo.py -- do not edit.\n#pragma once\n#include <stdint.h>\n")
        f.write("#define LOGO_W %d\n#define LOGO_H %d\n" % (w, h))
        f.write("// 2 bits per pixel, 4 per byte, LSB first: 0 clear 1 yellow 2 blue 3 navy\n")
        f.write("static const uint8_t LOGO_BITS[] = {\n  " + ",\n  ".join(lines) + "\n};\n")
    print("logo.h: %dx%d, %d bytes" % (w, h, len(data)))


main()
