#!/usr/bin/env python3
"""Rasterise the UI font (SIL OFL, tools/fonts/) into uifont.h.

ASCII 32..126 only; zh/ko keep using the 12x12 table in cjkfont.h. Each glyph
is a 4-bit coverage mask (two pixels per byte) that the firmware blends
against whatever is already in the framebuffer, so edges are antialiased
without needing to know the background colour.

    python3 tools/gen_font.py [nunito|fredoka]
"""
import os
from PIL import Image, ImageDraw, ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))
import sys
# name -> (file, variation axes in the font's own order)
FONTS = {"nunito": ("Nunito.ttf", [800]), "fredoka": ("Fredoka.ttf", [600, 100])}
CHOICE = sys.argv[1] if len(sys.argv) > 1 else "fredoka"
TTF = os.path.join(HERE, "fonts", FONTS[CHOICE][0])
OUT = os.path.join(HERE, "..", "uifont.h")
SIZES = {"UIF_TINY": 16, "UIF_SMALL": 22, "UIF_MID": 28, "UIF_BIG": 36, "UIF_HUGE": 64}   # px, em size


def build(name, px):
    font = ImageFont.truetype(TTF, px)
    font.set_variation_by_axes(FONTS[CHOICE][1])
    glyphs, blob = [], bytearray()
    for cp in range(32, 127):
        ch = chr(cp)
        adv = round(font.getlength(ch))
        bb = font.getbbox(ch, anchor="ls")          # relative to baseline origin
        w, h = bb[2] - bb[0], bb[3] - bb[1]
        if cp == 32 or w <= 0 or h <= 0:
            glyphs.append((len(blob), 0, 0, 0, 0, adv))
            continue
        img = Image.new("L", (w, h), 0)
        ImageDraw.Draw(img).text((-bb[0], -bb[1]), ch, font=font, fill=255, anchor="ls")
        px_ = [v >> 4 for v in img.getdata()]
        if len(px_) % 2: px_.append(0)
        off = len(blob)
        for i in range(0, len(px_), 2):
            blob.append((px_[i] << 4) | px_[i + 1])
        glyphs.append((off, w, h, bb[0], bb[1], adv))
    asc = -min(g[4] for g in glyphs if g[2])
    desc = max(g[4] + g[2] for g in glyphs if g[2])
    return name, glyphs, blob, asc, desc


def main():
    o = ["#pragma once\n#include <stdint.h>\n\n",
         "// GENERATED by tools/gen_font.py from %s (SIL OFL 1.1)" % CHOICE + " -- do not edit.\n\n",
         "struct UiGlyph { uint32_t off; uint8_t w, h; int8_t xo, yo; uint8_t adv; };\n",
         "struct UiFont { const UiGlyph *g; const uint8_t *bits; int8_t ascent; uint8_t height; };\n\n"]
    for name, px in SIZES.items():
        n, glyphs, blob, asc, desc = build(name, px)
        o.append("static const uint8_t %s_BITS[] = {" % n)
        o.append(",".join(str(b) for b in blob) + "};\n")
        o.append("static const UiGlyph %s_G[95] = {\n" % n)
        for off, w, h, xo, yo, adv in glyphs:
            o.append("  {%d,%d,%d,%d,%d,%d},\n" % (off, w, h, xo, yo, adv))
        o.append("};\n")
        o.append("static const UiFont %s = {%s_G, %s_BITS, %d, %d};\n\n" % (n, n, n, asc, asc + desc))
        print(n, px, "px:", len(blob), "bytes, ascent", asc, "height", asc + desc)
    open(OUT, "w").write("".join(o))


if __name__ == "__main__":
    main()
