#!/usr/bin/env python3
"""Generates dex.h (the Pokedex table for the firmware) from dex_data.py.

  python3 tools/gen_dex.py
"""
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from dex_data import DEX, TYPE_ACCENTS, CLASSIC, RARE, LEGENDARY, REGIONS, EEVEE_BRANCHES
from dex_stats import BASE_STATS
from dex_types import TYPES, TYPE_ORDER, CHART


def rgb565(hexcol):
    r, g, b = int(hexcol[1:3], 16), int(hexcol[3:5], 16), int(hexcol[5:7], 16)
    return (r >> 3) << 11 | (g >> 2) << 5 | (b >> 3)


# background biome by type (the light comes from the real RTC time)
# 0 PRADERA, 1 PLAYA, 2 BOSQUE, 3 VOLCAN, 4 MONTANA, 5 NIEVE
TYPE_BIOME = {
    'agua': 1, 'planta': 2, 'bicho': 2, 'fuego': 3,
    'roca': 4, 'tierra': 4, 'dragon': 1, 'hielo': 5,  # gen 1 dragons (Dratini) live in the water
    'normal': 0, 'electrico': 0, 'lucha': 0, 'veneno': 0,
    'psiquico': 0, 'fantasma': 0,
    # Gen 2/3 brought types no Gen 1 species had as a primary. Steel goes to the
    # mountain (Steelix, Aron, Registeel are all cave/rock creatures), Dark to
    # the forest (Umbreon, Houndour, Poochyena), Fairy to the meadow, and Flying
    # to the meadow as well -- nothing in 1-386 is primarily Flying, but the map
    # must be total or gen_dex.py raises on the first species that is.
    'acero': 4, 'siniestro': 2, 'hada': 0, 'volador': 0,
}

# exceptions by dex# (the type is not enough): marine rock/water fossils -> beach
BIOME_OVERRIDE = {138: 1, 139: 1, 140: 1, 141: 1}  # Omanyte, Omastar, Kabuto, Kabutops


def main():
    out = []
    out.append("#pragma once\n#include <stdint.h>\n\n")
    out.append("// GENERATED by tools/gen_dex.py from tools/dex_data.py - do not edit\n\n")
    out.append("#define DEX_COUNT %d\n" % len(DEX))
    out.append("#define DEX_EEVEE 133\n")
    # Emitted rather than written into the firmware by hand: gen_dex.py uses this
    # same list to decide which species are evolution-only, so a branch that can
    # be reached must also be one that cannot hatch, and vice versa.
    out.append("// EEVEE's branches. DexEntry holds ONE evolvesTo (134), so the other\n"
               "// seven cannot live in the table. Generated from EEVEE_BRANCHES in\n"
               "// dex_data.py, which is also what marks all eight evolution-only.\n")
    out.append("#define EEVEE_EVO_COUNT %d\n" % len(EEVEE_BRANCHES))
    out.append("static const int16_t EEVEE_EVOS[EEVEE_EVO_COUNT] = { %s };\n\n"
               % ', '.join(str(x) for x in EEVEE_BRANCHES))
    out.append("// The 18 current types. See tools/dex_types.py for why this game uses the\n"
               "// modern chart rather than the Gen 1 one.\n"
               "enum PkType : uint8_t {\n  ")
    out.append(", ".join("T_" + t.upper() for t in TYPE_ORDER))
    out.append(",\n  T_NONE = 255\n};\n#define TYPE_COUNT %d\n\n" % len(TYPE_ORDER))

    # effectiveness matrix, stored as tenths so it stays integer maths on the
    # MCU: 0 = immune, 5 = half, 10 = neutral, 20 = double
    out.append("// Type chart in TENTHS (0 immune, 5 not-very, 10 neutral, 20 super).\n"
               "// Multiplying the two defender columns gives a percentage directly:\n"
               "// 20*20 = 400 (4x), 10*10 = 100 (1x), 5*10 = 50 (0.5x).\n")
    out.append("static const uint8_t TYPE_FX[TYPE_COUNT][TYPE_COUNT] = {\n")
    nonneutral = 0
    for atk in TYPE_ORDER:
        row = []
        for dfn in TYPE_ORDER:
            m = CHART.get(atk, {}).get(dfn, 1)
            if m != 1:
                nonneutral += 1
            row.append(str(int(m * 10)))
        out.append("  { %s },  // %s\n" % (", ".join(f"{v:>2}" for v in row), atk))
    out.append("};\n\n")
    print(f"type table: {len(TYPE_ORDER)}x{len(TYPE_ORDER)}, {nonneutral} non-neutral cells")
    out.append(
        "// rarity: 0 = evolution only, 1 = common, 2 = rare, 3 = legendary\n"
        "enum : uint8_t { R_EVO = 0, R_COMUN, R_RARO, R_LEGENDARIO };\n\n"
        "struct DexEntry {\n"
        "  const char *name;\n"
        "  uint16_t evolvesTo;   // dex number, 0 = final form (>255 with gen 2/3)\n"
        "  uint8_t evolveLevel;\n"
        "  uint8_t rarity;       // comes from an egg if > 0\n"
        "  uint16_t accent;      // RGB565 colour of the type for the UI\n"
        "  uint8_t bHp, bAtk, bDef, bSpe;  // current base stats (PokeAPI), not the gen 1 ones\n"
        "  uint8_t bSpA, bSpD;   // special attack/defence: the physical-special split\n"
        "                        // lives in the species, the individual only rolls 4 IVs\n"
        "  uint8_t biome;        // 0 meadow 1 beach 2 forest 3 volcano 4 mountain 5 snow\n"
        "  uint8_t type1, type2;  // current typing; type2 = T_NONE if single-typed\n"
        "};\n\n")
    # base forms = those that are nobody's evolution (Eevee's branches are)
    # Anything that is somebody's evolution target is evolution-ONLY and never
    # hatches. Eevee's branches have to be added by hand because DexEntry holds a
    # single evolvesTo -- this used to read `| {135, 136}`, which is why Espeon,
    # Umbreon, Leafeon, Glaceon and Sylveon were treated as base forms and came
    # out of eggs. The list lives in dex_data.py so the firmware shares it.
    evolved = {d[4] for d in DEX if d[4]} | set(EEVEE_BRANCHES)
    rarities = []
    out.append("static const DexEntry DEX_TBL[DEX_COUNT + 1] = {\n")
    out.append('  { "?", 0, 0, 0, 0x2946, 50, 50, 50, 50, 50, 50, 0 },  // 0: unused\n')
    for num, slug, display, typ, evo, lvl in DEX:
        acc = rgb565(TYPE_ACCENTS[typ])
        if num in evolved:
            rar = 'R_EVO'
        elif num in LEGENDARY:
            rar = 'R_LEGENDARIO'
        elif num in RARE:
            rar = 'R_RARO'
        else:
            rar = 'R_COMUN'
        rarities.append(rar)
        hp, atk, df, spe, spa, spd = BASE_STATS[num]
        bio = BIOME_OVERRIDE.get(num, TYPE_BIOME[typ])
        t1, t2 = TYPES[num]
        c1 = "T_" + t1.upper()
        c2 = ("T_" + t2.upper()) if t2 else "T_NONE"
        dual = f"/{t2}" if t2 else ""
        out.append(f'  {{ "{display}", {evo}, {lvl}, {rar}, 0x{acc:04X}, {hp}, {atk}, {df}, {spe},'
                   f' {spa}, {spd}, {bio}, {c1}, {c2} }},  // {num} {t1}{dual}\n')
    out.append("};\n\n")
    out.append("// the game's first egg: classic starters\n")
    out.append("static const int16_t CLASSIC_DEX[] = { %s };\n" % ", ".join(map(str, CLASSIC)))
    out.append(f"#define NUM_CLASSIC_DEX {len(CLASSIC)}\n")

    # Regions. The last entry is ALL: the union, generated rather than written,
    # so it cannot drift out of step with the others.
    allstart = sorted({d for _n, _lo, _hi, st in REGIONS for d in st})
    out.append("\n// Which generation an egg may come from. A region is decided by the BASE\n"
               "// species, and evolutions follow wherever they lead.\n")
    out.append("struct RegionInfo {\n  const char *name;\n  uint16_t lo, hi;\n"
               "  const int16_t *starters;\n  uint8_t starterCount;\n};\n")
    for name, lo, hi, st in REGIONS:
        out.append("static const int16_t REGION_START_%s[] = { %s };\n"
                   % (name, ", ".join(map(str, st))))
    out.append("static const int16_t REGION_START_ALL[] = { %s };\n"
               % ", ".join(map(str, allstart)))
    out.append("#define REGION_COUNT %d\n" % (len(REGIONS) + 1))
    out.append("#define REGION_ALL %d\n" % len(REGIONS))
    out.append("static const RegionInfo REGIONS[REGION_COUNT] = {\n")
    for name, lo, hi, st in REGIONS:
        out.append('  { "%s", %d, %d, REGION_START_%s, %d },\n'
                   % (name, lo, hi, name, len(st)))
    out.append('  { "ALL", %d, %d, REGION_START_ALL, %d },\n'
               % (min(r[1] for r in REGIONS), max(r[2] for r in REGIONS), len(allstart)))
    out.append("};\n")
    from collections import Counter
    c = Counter(rarities)
    print(f"bases: {c['R_COMUN']} common, {c['R_RARO']} rare, {c['R_LEGENDARIO']} legendary, {c['R_EVO']} evolution-only")

    path = os.path.join(os.path.dirname(__file__), '..', 'dex.h')
    open(path, 'w').write(''.join(out))
    print(f"saved {os.path.normpath(path)} ({len(DEX)} species)")


if __name__ == '__main__':
    main()
