#!/usr/bin/env python3
"""Builds cjkfont.h: a 12x12 bitmap subset for the Chinese and Korean UI.

The panel's stock font is a 5x7 ASCII bitmap, so zh/ko text needs its own
glyphs. Embedding a whole CJK font would cost megabytes of a 3 MB app slot;
only the characters the UI actually uses are needed, a few hundred, so this
scans the firmware sources for every non-ASCII codepoint and emits just those.

Source art is Fusion Pixel Font 12px (SIL OFL 1.1, TakWolf/fusion-pixel-font),
BDF release. It is fetched on first use (curl, like the sprite tools) and kept
in tools/cache/. Hanzi come from the zh_hans cut, hangul from the ko cut.

    python3 tools/gen_cjk.py            # regenerate cjkfont.h
    python3 tools/gen_cjk.py --check    # exit 1 if cjkfont.h is stale

Re-run after adding or editing any zh/ko string. i18n_test fails on a string
that uses a codepoint missing from the table.
"""
import os, re, subprocess, sys, zipfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CACHE = os.path.join(ROOT, "tools", "cache")
VER = "2026.09.25"
URL = ("https://github.com/TakWolf/fusion-pixel-font/releases/download/"
       f"{VER}/fusion-pixel-font-12px-monospaced-bdf-v{VER}.zip")
SOURCES = ["i18n.cpp", "TamaPoke.ino"]
CELL = 12


def fetch():
    os.makedirs(CACHE, exist_ok=True)
    zp = os.path.join(CACHE, "fusion-pixel-12px-bdf.zip")
    if not os.path.exists(zp):
        subprocess.check_call(["curl", "-fsSL", "-o", zp, URL])
    with zipfile.ZipFile(zp) as z:
        for n in z.namelist():
            if n.endswith(".bdf") and ("zh_hans" in n or "-ko" in n):
                out = os.path.join(CACHE, os.path.basename(n))
                if not os.path.exists(out):
                    z.extract(n, CACHE)
                    if os.path.join(CACHE, n) != out:
                        os.replace(os.path.join(CACHE, n), out)


def parse_bdf(path):
    """-> {codepoint: [12 row ints]}, each row 12 bits, MSB = leftmost pixel."""
    glyphs, asc = {}, 10
    cur = None
    with open(path, encoding="utf-8") as f:
        for line in f:
            p = line.split()
            if not p:
                continue
            if p[0] == "FONT_ASCENT":
                asc = int(p[1])
            elif p[0] == "STARTCHAR":
                cur = {"bits": []}
            elif cur is not None and p[0] == "ENCODING":
                cur["cp"] = int(p[1])
            elif cur is not None and p[0] == "BBX":
                cur["w"], cur["h"], cur["xo"], cur["yo"] = map(int, p[1:5])
            elif cur is not None and p[0] == "BITMAP":
                cur["in"] = True
            elif cur is not None and p[0] == "ENDCHAR":
                cp = cur["cp"]
                if cp >= 0x80:
                    rows = [0] * CELL
                    top = asc - (cur["yo"] + cur["h"])
                    for i, hx in enumerate(cur["bits"]):
                        y = top + i
                        if not 0 <= y < CELL:
                            continue
                        nbits = len(hx) * 4
                        v = int(hx, 16) if hx else 0
                        for x in range(cur["w"]):
                            if v >> (nbits - 1 - x) & 1:
                                px = x + cur["xo"]
                                if 0 <= px < CELL:
                                    rows[y] |= 1 << (CELL - 1 - px)
                    glyphs[cp] = rows
                cur = None
            elif cur is not None and cur.get("in"):
                cur["bits"].append(p[0])
    return glyphs


def used_codepoints():
    cps = set()
    for s in SOURCES:
        with open(os.path.join(ROOT, s), encoding="utf-8") as f:
            for ch in f.read():
                if ord(ch) > 0x7F:
                    cps.add(ord(ch))
    return sorted(cps)


def is_hangul(cp):
    return 0xAC00 <= cp <= 0xD7A3 or 0x1100 <= cp <= 0x11FF or 0x3130 <= cp <= 0x318F


def render():
    fetch()
    hans = parse_bdf(os.path.join(CACHE, "fusion-pixel-12px-monospaced-zh_hans.bdf"))
    ko = parse_bdf(os.path.join(CACHE, "fusion-pixel-12px-monospaced-ko.bdf"))
    cps = used_codepoints()
    out = ["// GENERATED by tools/gen_cjk.py -- do not edit.",
           "// 12x12 subset of Fusion Pixel Font (SIL OFL 1.1) for the zh/ko UI.",
           "// One row per scanline, 12 bits, MSB = leftmost pixel.",
           "#pragma once", "#include <stdint.h>", ""]
    missing = []
    table = []
    for cp in cps:
        order = (ko, hans) if is_hangul(cp) else (hans, ko)
        g = next((d[cp] for d in order if cp in d), None)
        if g is None:
            missing.append(cp)
        else:
            table.append((cp, g))
    if missing:
        sys.exit("no glyph for: " + " ".join("U+%04X %s" % (c, chr(c)) for c in missing))
    out.append("#define CJK_COUNT %d" % len(table))
    out.append("static const uint16_t CJK_CP[CJK_COUNT] = {")
    for i in range(0, len(table), 12):
        out.append("  " + ", ".join("0x%04X" % c for c, _ in table[i:i + 12]) + ",")
    out.append("};")
    out.append("static const uint16_t CJK_BITS[CJK_COUNT][%d] = {" % CELL)
    for cp, g in table:
        out.append("  {" + ",".join("0x%03X" % r for r in g) + "},  // U+%04X %s" % (cp, chr(cp)))
    out.append("};")
    return "\n".join(out) + "\n", len(table)


if __name__ == "__main__":
    text, n = render()
    path = os.path.join(ROOT, "cjkfont.h")
    if "--check" in sys.argv:
        cur = open(path, encoding="utf-8").read() if os.path.exists(path) else ""
        sys.exit(0 if cur == text else 1)
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)
    print("cjkfont.h: %d glyphs, %d bytes" % (n, n * 24 + n * 2))
